### ISSUE TITLE
[Compatibility] 与Multiverse-Core不兼容

### ISSUE THREAD

**Issue by nanmenyangde** [Xzavier0722/SlimeGlue#11]
## Description / 描述
Slimefun机器在被Multiverse-Core重置的世界中不工作。

## Incompatible plugin information / 不兼容插件信息
插件名称: Multiverse-Core
插件版本:4.3.2-SNAPSHOT
发布网址:http://ci.onarandombox.com/job/Multiverse-Core/
源码地址:https://github.com/Multiverse/Multiverse-Core

环境
粘液科技版本: vc97d6a5-canary
操作系统:Windows10
服务器核心 (Spigot/Paper/etc.):Paper
服务器版本:1.18.2
插件列表:Slimefun,Multiverse-Core

**Comment by nanmenyangde** [comment]
目前只尝试了需要电力的机器，还没有看基础机器能不能用，我会再试一下

**Comment by Xzavier0722** [comment]
请说明一下重置的操作指的是什么，并提供详细复现步骤与现象。

**Comment by nanmenyangde** [comment]
我对一个叫做kingdoms的世界进行操作的时候：
重置 指 /mv regen kingdoms

重置之后，世界会重新生成
这时候在世界里面放置：

- 能量分配器 会一直显示正在连接
- 电炉无法打开GUI
当我放置充能太阳能发电机，电炉，能量分配器时 服务器后台显示[Server thread/WARN]: [Slimefun] Could not set Block info for non-registered World 'kingdoms'. Is some plugin trying to store data in a fake world?

**Comment by Xzavier0722** [comment]
这个问题主要原因是粘液本体的逻辑，作为附属来修复可能会用到一些非常规手段，并不合适。

**Comment by nanmenyangde** [comment]
那如果我想要用这个功能，请问我是应该去粘液还是去mvcore发issue?
@Xzavier0722
