### ISSUE TITLE
[Compatibility] Bentobox的附属CaveBlock边界问题

### ISSUE THREAD

**Issue by DongShaoNB** [Xzavier0722/SlimeGlue#16]
## Description / 描述
Please describe the issue in detail. 
请详细描述遇到的问题。 

爆炸镐可破坏Bentobox附属Caveblock屏障外方块
演示视频：https://www.bilibili.com/video/BV14d4y1D7YS/

## Incompatible plugin information / 不兼容插件信息
Plugin name / 插件名称:Bentobox / CaveBlock
Plugin version / 插件版本:1.20.1 / 1.16.0
Publish website / 发布网址:https://www.spigotmc.org/resources/bentobox-bskyblock-acidisland-skygrid-caveblock-aoneblock-boxed.73261/
Source code / 源码地址:https://github.com/BentoBoxWorld/BentoBox 和 https://github.com/BentoBoxWorld/CaveBlock

## Environment  / 环境
Slimefun version / 粘液科技版本: 2022.07
OS / 操作系统: Windows Server 2022
Server brand / 服务器核心 (Spigot/Paper/etc.): PurPur
Server version / 服务器版本:1.19
Plugin list / 插件列表:

**Comment by Xzavier0722** [comment]
该问题是bentobox系列全部有问题还是只有该附属？

**Comment by DongShaoNB** [comment]
> 该问题是bentobox系列全部有问题还是只有该附属？

这个没测试
