### ISSUE TITLE
[BUG] 魔法插件、粘液科技、粘液胶三个插件一起装，矿工机器人不能破坏任何物品。

### ISSUE THREAD

**Issue by XXY233** [Xzavier0722/SlimeGlue#22]
## Description / 描述

魔法插件、粘液科技、粘液胶三个插件一起装，矿工机器人不能破坏任何物品。
测试时，删除粘液胶或者魔法插件任意之一，矿工机器人就可以正常工作。

## Environment  / 环境
Slimefun version / 粘液科技版本: Slimefun-v5116ff5-canary
Plugin version / 插件版本: SlimeGlue-exp-430f173
OS / 操作系统:
Server brand / 服务器核心 (Spigot/Paper/etc.): PaperSpigot
Server version / 服务器版本: 1.19.3
Plugin list / 插件列表: Magic, Slimefun, SlimeGlue

没有任何报错，这是日志：https://paste.gg/p/anonymous/c0214a1595da40b2a96e21fd61209d31

**Comment by Xzavier0722** [comment]
已修复，请使用最新exp版本测试确认。

**Comment by XXY233** [comment]
没问题了，谢谢！
