### ISSUE TITLE
箱子锁能使用货运系统

### ISSUE THREAD

**Issue by A1exey1337** [Xzavier0722/SlimeGlue#25]
箱子锁上锁之后能使用粘液科技货运系统运输物品 

## Incompatible plugin information / 不兼容插件信息
Plugin name / 插件名称: LockettePro
Plugin version / 插件版本: 2.9.2
Publish website / 发布网址: https://www.mcbbs.net/forum.php?mod=viewthread&tid=869145
Source code / 源码地址: https://github.com/Soldier233/LockettePro

## Environment  / 环境 Java 18
Slimefun version / 粘液科技版本: Slimefun-va88d0e0-canary
OS / 操作系统: Windows10
Server brand / 服务器核心 (Spigot/Paper/etc.): Paper 1.16.5-794
Server version / 服务器版本: 1.16.5
Plugin list / 插件列表:  
+ PlaceholderAPI 2.11.1
  + ChatEmojis 2.3.2
  + HolographicDisplays 3.0.1
  + antiRedstoneClock 1.5.0
  + GSit 1.3.6
  + ViaVersion 4.5.1
  + ViaBackwards 4.5.1
  + LuckPerms 5.4.40
  + ClearLag 3.2.2
  + LaggRemover 2.0.6
  + ProtocolLib 5.0.0-SNAPSHOT-b612
  + LiteSignIn 1.6.5.2
  + MiaoBoard 2.6.0-git-00db90be472bcc688847491a33f195cc5637bbd1
  + AntiSeedCracker 1.0
  + CowSuperJoin 1.76
  + Vault 1.7.3-b131
  + EastLandLog4jFixer 1.0.4
  + ViaRewind 2.0.2
  + LiteAnnouncer 1.3.0
  + MiaoChat 2.1.2
  + DaeFase 1.0.0
  + AlonsoLevels 2.2.4-BETA-PRO
  + DoomsdayVerify 1.3
  + WorldEdit 7.2.13+46576cc
  + Essentials 2.19.7
  + GrimAC 2.3.35
  + XConomy 2.19.5
  + LiteBans 2.10.4
  + Multiverse-Core 4.3.1-b861
  + RedPacket 1.5.8
  + DeluxeMenus 1.13.3-Release
  + TAB 3.1.5
  + ItemJoin 5.2.5-RELEASE-b850
  + SuperVanish 6.2.15
  + EazyNick 3.14.7
  + Images 2.2.8
  + Slimefun 3acb960-canary
  + EcoPower Build 1 zh-CN(ybw0014) (git eca8ab1)
  + EssentialsProtect 2.19.7
  + EssentialsSpawn 2.19.7
  + CoreProtect 21.3
  + GuizhanLibPlugin Build 19 (git 368ae3f)
  + ExtraGear Build 2 zh-CN(ybw0014) (git ff13031)
  + CMILib 1.2.4.4
  + Residence 5.1.1.0
  + HotbarPets Build 3 zh-CN(ybw0014) (git 92415a4)
  + SlimefunOreChunks Build 1 zh-CN(ybw0014) (git 67879ed)
  + ElectricSpawners Build 4 zh-CN(ybw0014) (git 0d7b9bb)
  + QuickShop 5.1.1.2
  + PrivateStorage Build 1 zh-CN(ybw0014) (git 7205ea3)
  + DyedBackpacks Build 2 zh-CN(baoad) (git 3a17d71)
  + LockettePro 2.9.2
  + SlimeGlue 1.0.1-d107917
  + PlugManX 2.3.0

**Comment by Xzavier0722** [comment]
请更新最新exp版本后确认是否修复，如确认修复后请关票。
此外，由于lib更新，建议将sf也再更新至exp版本。
