### ISSUE TITLE
[Compatibility]和王国不兼容

### ISSUE THREAD

**Issue by DenNotFound** [Xzavier0722/SlimeGlue#3]
## Description / 描述
A王国的玩家可以用机器人挖掘B王国的东西

## Incompatible plugin information / 不兼容插件信息
Plugin name / 插件名称:KingdomsX
Plugin version / 插件版本:1.12.6.3.1
Publish website / 发布网址:https://www.spigotmc.org/resources/kingdomsx.77670/
Source code / 源码地址:https://github.com/CryptoMorin/KingdomsX/

## Environment  / 环境
Slimefun version / 粘液科技版本:4.9-release-2022.03.2
OS / 操作系统:Windows
Server brand / 服务器核心 (Spigot/Paper/etc.):paper
Server version / 服务器版本:1.17.1
Plugin list / 插件列表:Slimefun, KingdomsX 就这俩

**Comment by Xzavier0722** [comment]
该插件为闭源付费插件，且未提供API，暂时无法提供支持。请尝试联系官方进行兼容。

**Comment by DenNotFound** [comment]
> 

本插件提供API,详情请见https://github.com/CryptoMorin/KingdomsX/wiki/API

**Comment by Xzavier0722** [comment]
收到，之前没有仔细看wiki，只是在主页浏览了下没看到api相关字样就关了。

**Comment by Xzavier0722** [comment]
请使用release中的exp版本协助验证问题是否被修复，并反馈结果，谢谢。

**Comment by DenNotFound** [comment]
现在机器人无法破坏方块，但是仍能进入其他王国领地，且屠夫机器人可以越过土地保护权限击杀其他王国领地内动物。

**Comment by DenNotFound** [comment]
> 请使用release中的exp版本协助验证问题是否被修复，并反馈结果，谢谢。

现在机器人无法破坏方块，但是仍能进入其他王国领地，且屠夫机器人可以越过土地保护权限击杀其他王国领地内动物。

**Comment by DenNotFound** [comment]
> 请使用release中的exp版本协助验证问题是否被修复，并反馈结果，谢谢。

而且现在矿工/樵夫等破坏方块的机器人在无主之地和自己王国的土地都无法使用

**Comment by DenNotFound** [comment]
> 请使用release中的exp版本协助验证问题是否被修复，并反馈结果，谢谢。

王国也有自带权限编辑，请问能否把机器人的编辑权限与王国同时有交互/破坏权限的玩家联动呢？

**Comment by Xzavier0722** [comment]
> > 请使用release中的exp版本协助验证问题是否被修复，并反馈结果，谢谢。
> 
> 现在机器人无法破坏方块，但是仍能进入其他王国领地，且屠夫机器人可以越过土地保护权限击杀其他王国领地内动物。



> > 请使用release中的exp版本协助验证问题是否被修复，并反馈结果，谢谢。
> 
> 而且现在矿工/樵夫等破坏方块的机器人在无主之地和自己王国的土地都无法使用

请再次下载exp版本尝试验证这两个问题，由于我对该插件并无基本概念可能需要调整多次，还望理解。



> > 请使用release中的exp版本协助验证问题是否被修复，并反馈结果，谢谢。
> 
> 王国也有自带权限编辑，请问能否把机器人的编辑权限与王国同时有交互/破坏权限的玩家联动呢？

对于该问题，虽然可以实现但方案并不是常规做法，且该功能偏向于定制化。此类功能修改sf本体来兼容是更合适高效的选择。在本插件应该不会做此项兼容。

**Comment by DenNotFound** [comment]
樵夫和矿工现在好使了，但是屠宰仍能越过权限。

**Comment by DenNotFound** [comment]
可能我表述的不是很准确。我的意思是所有破坏方块的机器人都能越过权限，包括樵夫，而不仅仅包括矿工，樵夫。

**Comment by DenNotFound** [comment]
还有一个问题，王国的结构是原版方块，但是右键弹出gui,如果机器人挖掘了结构，盔甲架还在，在原位置上放任一方块再破坏会掉落结构，可以用这个来刷物品，比如提取器是绿宝石，机器人挖了绿宝石块，我在原地放土块，挖掘掉落提取器，就拿土块刷了绿宝石块，这个有方法避免吗?

**Comment by Xzavier0722** [comment]
> 樵夫和矿工现在好使了，但是屠宰仍能越过权限。

该问题大概是粘液本体那边没有检测权限导致，我在中文版仓库提交了一版修复，你可以配合 [粘液中文版](https://github.com/StarWishsama/Slimefun4) 的exp版本测试下。
_
> 还有一个问题，王国的结构是原版方块，但是右键弹出gui,如果机器人挖掘了结构，盔甲架还在，在原位置上放任一方块再破坏会掉落结构，可以用这个来刷物品，比如提取器是绿宝石，机器人挖了绿宝石块，我在原地放土块，挖掘掉落提取器，就拿土块刷了绿宝石块，这个有方法避免吗?

如果对方是开源项目，我很容易可以看到对应的实现提取到识别特征来修复这个问题。但是对方是闭源的，api文档的描述也非常不完整。在后面可能可以尝试下，但是不一定可以兼容。

**Comment by DenNotFound** [comment]
有api的，麻烦看一下https://github.com/CryptoMorin/KingdomsX/wiki/API




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月17日(星期天) 下午2:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Xzavier0722/SlimeGlue] [Compatibility]和王国不兼容 (Issue #3)





 
该插件为闭源付费插件，且未提供API，暂时无法提供支持。请尝试联系官方进行兼容。
