### ISSUE TITLE
[Compatibility]与PixelPlayerWorld领地插件兼容问题

### ISSUE THREAD

**Issue by 115881128** [Xzavier0722/SlimeGlue#39]
## Description / 描述
Please describe the issue in detail. 
使用PixelPlayerWorld领地插件,粘液科技任意 机器 背包 头颅类的物品都可以在该领地世界放置,且挖掉直接变成普通头颅.

## Incompatible plugin information / 不兼容插件信息
Plugin name / 插件名称:PixelPlayerWorld
Plugin version / 插件版本:3.1.0beta
Publish website / 发布网址:https://www.mcbbs.net/thread-1449338-1-1.html
Source code / 源码地址:无

## Environment  / 环境
Slimefun version / 粘液科技版本:Slimefun 9921b3f-Insider
OS / 操作系统:Windows Server 2022 Standard
Server brand / 服务器核心 (Spigot/Paper/etc.):purpur
Server version / 服务器版本:1.20.1
Plugin list / 插件列表:XConomy,Vault,TrChat,Invero,HuskHomes,PixelPlayerWorld,Slimefun,PlaceholderAPI,ProtocolLib

**Comment by StarWishsama** [comment]
对应插件没有提供对外 API 供我们检测
